### ISSUE TITLE
Unable to retrieve a valid package!

### ISSUE THREAD

**Issue by stevepm** [chef/omnitruck#193]
I'm following this tutorial: https://learn.chef.io/learn-the-basics/rhel/set-up-your-own-server/

I'm on step 5: https://learn.chef.io/learn-the-basics/rhel/set-up-your-own-server/#step5

This is the full output that I'm getting:

```
[vagrant@localhost ~]$ curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19824  100 19824    0     0   103k      0 --:--:-- --:--:-- --:--:--  103k
el 7 x86_64
Getting information for chefdk current  for el...
downloading https://omnitruck.chef.io/current/chefdk/metadata?v=&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.11189/metadata.txt
trying wget...
sha1    a560201d1d0ad3eea2c1e95922f34a03bfd7f540
sha256  740aa79bd2310f83157ac2ea7aeff8b773f276e39a50cd77d06d49eac9f1960f
url     https://packages.chef.io/current/el/7/chefdk-0.18.6-1.el7.x86_64.rpm
version 0.18.6
downloaded metadata file looks valid...
downloading https://packages.chef.io/current/el/7/chefdk-0.18.6-1.el7.x86_64.rpm
  to file /tmp/install.sh.11189/chefdk-0.18.6-1.el7.x86_64.rpm
trying wget...
trying curl...
trying perl...
trying python...
Unable to retrieve a valid package!
Version:

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://omnitruck.chef.io/current/chefdk/metadata?v=&p=el&pv=7&m=x86_64
Download URL: https://packages.chef.io/current/el/7/chefdk-0.18.6-1.el7.x86_64.rpm
\nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2016-08-25 00:37:21--  https://packages.chef.io/current/el/7/chefdk-0.18.6-1.el7.x86_64.rpm
Resolving packages.chef.io (packages.chef.io)... 151.101.40.65
Connecting to packages.chef.io (packages.chef.io)|151.101.40.65|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable: Back-end server is at capacity
2016-08-25 00:37:21 ERROR 503: Service Unavailable: Back-end server is at capacity.\n\nSTDERR from curl:\n\nHTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Fastly-Restarts: 1
Content-Length: 0
Accept-Ranges: bytes
Date: Thu, 25 Aug 2016 00:37:21 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-sjc3620-SJC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1472085441.905190,VS0,VE40

HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Fastly-Restarts: 1
Content-Length: 0
Accept-Ranges: bytes
Date: Thu, 25 Aug 2016 00:37:23 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-sjc3620-SJC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1472085442.959807,VS0,VE40

HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Fastly-Restarts: 1
Content-Length: 0
Accept-Ranges: bytes
Date: Thu, 25 Aug 2016 00:37:25 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-sjc3620-SJC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1472085445.008373,VS0,VE40

HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Fastly-Restarts: 1
Content-Length: 0
Accept-Ranges: bytes
Date: Thu, 25 Aug 2016 00:37:29 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-sjc3620-SJC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1472085449.059050,VS0,VE40

HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Fastly-Restarts: 1
Content-Length: 0
Accept-Ranges: bytes
Date: Thu, 25 Aug 2016 00:37:37 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-sjc3620-SJC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1472085457.102039,VS0,VE40

HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Fastly-Restarts: 1
Content-Length: 0
Accept-Ranges: bytes
Date: Thu, 25 Aug 2016 00:37:53 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-sjc3620-SJC
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1472085473.158659,VS0,VE40
\n\nSTDERR from perl:\n\nCan't locate LWP/Simple.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.\n\nSTDERR from python:\n\nTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable: Back-end server is at capacity\n
```

**Comment by sersut** [comment]
@stevepm We just had a blip in the infrastructure. Can you try again?

**Comment by tas50** [comment]
Closing this out since we never heard back
