### ISSUE TITLE
 ERROR 503: certificate has expired

### ISSUE THREAD

**Issue by willis7** [chef/omnitruck#337]
I just tried to build my vagrant machine this morning only to find an error about certificate expiry.

```
==> web: Installing chef...
==> web: debian 8 x86_64
==> web: Getting information for chef stable 12.17.44 for debian...
==> web: downloading https://omnitruck.chef.io/stable/chef/metadata?v=12.17.44&p=debian&pv=8&m=x86_64
==> web:   to file /tmp/install.sh.1060/metadata.txt
==> web: trying wget...
==> web: trying perl...
==> web: trying python...
==> web: Unable to retrieve a valid package!
==> web: Version: 12.17.44
==> web:
==> web: Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
==> web: Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
==> web: More Chef support resources can be found at https://www.chef.io/support
==> web:
==> web: Please include as many details about the problem as possible i.e., how to reproduce
==> web: the problem (if possible), type of the Operating System and its version, etc.,
==> web: and any other relevant details that might help us with troubleshooting.
==> web:
==> web: Metadata URL: https://omnitruck.chef.io/stable/chef/metadata?v=12.17.44&p=debian&pv=8&m=x86_64
==> web: \nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2017-11-14 13:30:54--  https://omnitruck.chef.io/stable/chef/metadata?v=12.17.44&p=debian&pv=8&m=x86_64
==> web: Resolving omnitruck.chef.io (omnitruck.chef.io)... 151.101.130.110, 151.101.194.110, 151.101.2.110, ...
==> web: Connecting to omnitruck.chef.io (omnitruck.chef.io)|151.101.130.110|:443... connected.
==> web: HTTP request sent, awaiting response... 503 certificate has expired
==> web: 2017-11-14 13:30:55 ERROR 503: certificate has expired.\n\nSTDERR from perl:\n\n503 certificate has expired <URL:https://omnitruck.chef.io/stable/chef/metadata?v=12.17.44&p=debian&pv=8&m=x86_64>\n\nSTDERR from python:\n\nTraceback (most recent call last):
==> web:   File "<string>", line 1, in <module>
==> web:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
==> web:     return opener.open(url, data, timeout)
==> web:   File "/usr/lib/python2.7/urllib2.py", line 437, in open
==> web:     response = meth(req, response)
==> web:   File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
==> web:     'http', request, response, code, msg, hdrs)
==> web:   File "/usr/lib/python2.7/urllib2.py", line 475, in error
==> web:     return self._call_chain(*args)
==> web:   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
==> web:     result = func(*args)
==> web:   File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
==> web:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
==> web: urllib2.HTTPError: HTTP Error 503: certificate has expired\n
```

Please advise if you need further information.

**Comment by axvm** [comment]
Yea, same problem here. Guys, wildcard ssl certificate (*.chef.io) has been expired. wtf is going on?

**Comment by thommay** [comment]
Thanks for the report, it's being worked on. We'll provide further information as we have it.

**Comment by jodyfanning** [comment]
Slightly related, but omnitruck isn't included in the [Chef status page ](https://status.chef.io/) either. It took a bit of googling to arrive here.

**Comment by abednarik** [comment]
Yeah, same here a few minutes googling to found this and get a proper status about this issue.

**Comment by jonattta** [comment]
same for me

**Comment by sterago** [comment]
I see that one may work around it using `chef_omnibus_url`, at least for those using test kitchen, but is there a valid alternative URL? (https://docs.chef.io/config_yml_kitchen.html)

**Comment by jonattta** [comment]
it's working again for me as well

**Comment by willis7** [comment]
I can confirm it's working for me too.

**Comment by BenMitchell1979** [comment]
Follow-up workaround. As a test, I was able to get past the certificate issue by hardcoding the URL in my .kitchen.yml file as HTTP. So if this happens again - this will let us keep testing. 

provisioner:
  name: chef_zero
  product_name: chef
  chef_omnibus_url: http://omnitruck.chef.io/install.ps1

**Comment by thommay** [comment]
@BenMitchell1979 i deleted your comment since that's not something we're going to encourage people to do.
