### ISSUE TITLE
Chef Tutorial - Chefdk 2.5.3 - Unable to retrieve a valid package! 

### ISSUE THREAD

**Issue by githublarryl** [chef/omnitruck#359]
Following "Set up a virtual machine to manage"
URL: https://learn.chef.io/modules/learn-the-basics/rhel/virtualbox/set-up-a-machine-to-manage#/
Current Step: 8 "Install the Chef DK on your CentOS instance"

I am behind a proxy

Full text:

**Attempt following base instructions:**
```
[vagrant@localhost ~]$ curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -c stable -v 2.5.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Attempt using --insecure flag**
```
[vagrant@localhost ~]$ curl **--insecure** https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -c stable -v 2.
5.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23429  100 23429    0     0  71328      0 --:--:-- --:--:-- --:--:-- 71212
el 7 x86_64
Getting information for chefdk stable 2.5.3 for el...
downloading https://omnitruck.chef.io/stable/chefdk/metadata?v=2.5.3&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.2685/metadata.txt
trying wget...
trying curl...
trying perl...
trying python...
**Unable to retrieve a valid package!**
Version: 2.5.3

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://omnitruck.chef.io/stable/chefdk/metadata?v=2.5.3&p=el&pv=7&m=x86_64
\nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2018-06-22 16:47:56--  https://omnitruck.chef.io/stable/chefdk/metadata?v=2.5.3&p=el&pv=7&m=x86_64
Resolving omnitruck.chef.io (omnitruck.chef.io)... 151.101.50.110
Connecting to omnitruck.chef.io (omnitruck.chef.io)|151.101.50.110|:443... connected.
ERROR: cannot verify omnitruck.chef.io's certificate, issued by ‘/C=US/O=Texas CPA/OU=IT/CN=caupneif08.core.cpa.state.tx.us’:
  Unable to locally verify the issuer's authority.
To connect to omnitruck.chef.io insecurely, use `--no-check-certificate'.\n\nSTDERR from curl:\n\n\n\nSTDERR from perl:\n\nCan't locate LWP/Simple.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.\n\nSTDERR from python:\n\nTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>\n
```

**Comment by qaispak** [comment]
I am getting the same error. Does anyone know the solution for this?

**Comment by jtimberman** [comment]
What CentOS version are you using? Where did you get the vagrant VM, and which Vagrant provider are you using for it?

**Comment by jtimberman** [comment]
After a second glance, it appears it may be an issue with your proxy configuration.

```
ERROR: cannot verify omnitruck.chef.io's certificate, issued by ‘/C=US/O=Texas CPA/OU=IT/CN=caupneif08.core.cpa.state.tx.us’:
```
