### ISSUE TITLE
Failed to verify SSL certificate installing Chef DK

### ISSUE THREAD

**Issue by qaisbadsha** [chef/omnitruck#377]
I am trying to follow the tutorials and running this command on Centos:

`curl -k  https://omnitruck.chef.io/install.sh | bash -s -- -P chefdk -c stable -v 2.5.3
`
And I get this:

```
Getting information for chefdk stable 2.5.3 for el...
downloading https://omnitruck.chef.io/stable/chefdk/metadata?v=2.5.3&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.26/metadata.txt
trying curl...
trying python...
Unable to retrieve a valid package!
Version: 2.5.3

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://omnitruck.chef.io/stable/chefdk/metadata?v=2.5.3&p=el&pv=7&m=x86_64
\nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from curl:\n\n\n\nSTDERR from python:\n\nTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>\n

```

What is this issue? I played with my proxy but it shouldn't matter since it seems like the SSL certificate is not recognized.

**Comment by jakauppila** [comment]
I was running into this issue as well when attempting to install Cinc Workstation on WSL.

It turned out to be my proxy environment variables were not persisting into the sudo session, so I had to configure it to persist those environment variables as described here: https://askubuntu.com/a/19298

Is there some graceful way to notify/recognize when this is happening due to the sudoers configuration?
