### ISSUE TITLE
Can't install chef via "omnitruck" on Cumulus Linux 2.2

### ISSUE THREAD

**Issue by jaimegago** [chef/omnitruck#81]
Tried the "omnitruck" installer script on a Cumulus Linux 2.2.2 switch and it failed with a 500

```
cat /etc/lsb-release
DISTRIB_ID="Cumulus Networks"
DISTRIB_RELEASE=2.2.2
DISTRIB_DESCRIPTION=2.2.2-9ba1044-201411150933-build
```

```
Downloading Chef  for "cumulus networks"...
downloading https://www.opscode.com/chef/metadata?v=&prerelease=false&nightlies=false&p="cumulus networks"&pv=2.2.2&m=x86_64
  to file /tmp/install.sh.25912/metadata.txt
trying wget...
trying perl...
trying python...
Unable to retrieve a valid package!
Version:

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://www.opscode.com/chef/metadata?v=&prerelease=false&nightlies=false&p="cumulus networks"&pv=2.2.2&m=x86_64

DEBUG OUTPUT FOLLOWS:

STDERR from wget:

--2015-02-09 18:54:43--  https://www.opscode.com/chef/metadata?v=&prerelease=false&nightlies=false&p=%22cumulus
Resolving www.opscode.com (www.opscode.com)... 184.106.28.90
Connecting to www.opscode.com (www.opscode.com)|184.106.28.90|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2015-02-09 18:54:44 ERROR 500: Internal Server Error.

STDERR from perl:

Can't locate LWP/Simple.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

STDERR from python:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by lamont-granquist** [comment]
does the debian or ubuntu artifacts that we build even work with this?

if it does, then https://github.com/chef/opscode-omnitruck/blob/master/platforms.rb could be updated to remap the distro and version onto the artifact.

**Comment by jaimegago** [comment]
Currently I'm running the Chef version Cumulus makes available via [their repo](http://repo.cumulusnetworks.com/pool/CumulusLinux-2.2/addons/) which is fairly old (11.6) and wanted to upgrade to 12 via the "omnitruck" install script.

Here is the info on the amd64 package

```
dpkg -I chef_11.6.2-1_amd64.deb
 new debian package, version 2.0.
 size 33176330 bytes: control archive=264186 bytes.
     251 bytes,    11 lines      control
 1062827 bytes,  9882 lines      md5sums
    2956 bytes,   102 lines   *  postinst             #!/bin/sh
     945 bytes,    35 lines   *  postrm               #!/bin/sh
 Package: chef
 Version: 11.6.2-1
 License: unknown
 Vendor: vagrant@debian-7
 Architecture: amd64
 Maintainer: Chef Software, Inc.
 Installed-Size: 110457
 Section: default
 Priority: extra
 Homepage: http://www.getchef.com
 Description: The full stack of chef
```
HTH

**Comment by jtimberman** [comment]
Hello,

I'm sorry that we never followed up on this issue! As it is quite old and there have been many changes to the products and operating systems involved, I'm going to close this issue, as reproducing it would be difficult, if not impossible.

Cheers
Joshua
